// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ejercicio1AplicadaII.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Ejercicio1AplicadaII.Models.Estudiantes", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NacionalidadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Semestre")
                        .HasColumnType("INTEGER");

                    b.HasKey("EstudianteId");

                    b.HasIndex("NacionalidadId");

                    b.ToTable("Estudiante");
                });

            modelBuilder.Entity("Ejercicio1AplicadaII.Models.Nacionalidades", b =>
                {
                    b.Property<string>("NacionalidadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nacionalidad")
                        .HasColumnType("TEXT");

                    b.HasKey("NacionalidadId");

                    b.ToTable("Nacionalidad");
                });

            modelBuilder.Entity("Ejercicio1AplicadaII.Models.Estudiantes", b =>
                {
                    b.HasOne("Ejercicio1AplicadaII.Models.Nacionalidades", "Nacionallida")
                        .WithMany()
                        .HasForeignKey("NacionalidadId");
                });
#pragma warning restore 612, 618
        }
    }
}
